version: '3.8'

services:
  client1:
    build: ./client1
    container_name: my-project-app
    volumes:
      - ./client1:/app
    environment:
      - name=6000
    ports:
      - "6000:6000"
    networks:
      - my-network2
    depends_on:
      - postgresql-db
    
  postgresql-db:
    image: postgres:10

    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: P4ssword
      POSTGRES_DB: postgresql-database # postgresql-database-server
    ports:
      - "5436:5432"
    networks:
      - my-network2

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq2"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-network2

networks:
  my-network2:
    driver: bridge