version: '3.8'

services:
  client-app:
    build: ./client1
    container_name: my-project-app
    volumes:
      - ./client1:/client-app
    environment:
      - name=6000
    ports:
      - "6000:6000"
    networks:
      - my-network2
    depends_on:
      - database-app
      - rabbitmq

  database-app:
    build: ./database-app
    container_name: database-app
    volumes:
      - ./database-app:/app
    environment:
      - name=6002
    ports:
      - "6002:6002"
    networks:
      - my-network2
    depends_on:
      - postgresql-db

  provider-app:
    build: ./provider-app
    container_name: provider-app
    volumes:
      - ./provider-app:/app
    environment:
      - name=6001
    ports:
      - "6001:6001"
    networks:
      - my-network2
    depends_on:
      - rabbitmq
      - database-app

  postgresql-db:
    image: postgres:10
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: P4ssword
      POSTGRES_DB: postgresql-database
    ports:
      - "5436:5432"
    networks:
      - my-network2

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq2"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-network2

networks:
  my-network2:
    driver: bridge